#!/usr/bin/env bash
# Creates or updates a documentation sync PR in bolt-docs.
# Required env: PR_NUMBER, PR_TITLE, BOLT_DOCS_REPO, DOCS_SUBPATH, GH_TOKEN, GITHUB_OUTPUT
#
# Reads:  bolt-docs-patch/*.md, ai_pr_title.txt, ai_pr_body.txt
# Writes: GITHUB_OUTPUT docs_pr_url
set -euo pipefail

readonly BRANCH="react-native-sdk-sync/pr-${PR_NUMBER}"
readonly SDK_PR_URL="https://github.com/BoltApp/bolt-react-native-sdk/pull/${PR_NUMBER}"

# Clone bolt-docs. GH_TOKEN must be DOCS_WRITE_TOKEN (cross-repo access).
git clone \
  "https://x-access-token:${GH_TOKEN}@github.com/${BOLT_DOCS_REPO}.git" \
  bolt-docs-repo

cd bolt-docs-repo
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# Reset (or create) the sync branch from master.
# Force-push is intentional: this branch is fully owned by the sync workflow.
git checkout -B "$BRANCH" origin/master

# Apply AI-generated file patches
PATCHED=0
for FILE in ../bolt-docs-patch/*.md; do
  [ -f "$FILE" ] || continue  # guard against empty glob
  FILENAME=$(basename "$FILE")
  cp "$FILE" "${DOCS_SUBPATH}/${FILENAME}"
  echo "Applied: ${DOCS_SUBPATH}/${FILENAME}"
  PATCHED=$((PATCHED + 1))
done

if [ "$PATCHED" -eq 0 ] || git diff --quiet HEAD; then
  echo "No file changes after patching — skipping docs PR"
  echo "docs_pr_url=" >> "$GITHUB_OUTPUT"
  exit 0
fi

git add -A
git commit -m "docs(react-native): sync with bolt-react-native-sdk PR #${PR_NUMBER}

Triggered by: ${PR_TITLE}
SDK PR: ${SDK_PR_URL}"

git push --force origin "$BRANCH"

# Create the docs PR on first push; reuse it on subsequent commits.
EXISTING=$(gh pr list \
  --repo "$BOLT_DOCS_REPO" \
  --head "$BRANCH" \
  --json number \
  --jq '.[0].number // empty')

if [ -z "$EXISTING" ]; then
  PR_TITLE_TEXT=$(cat ../ai_pr_title.txt)
  {
    cat ../ai_pr_body.txt
    printf '\n\n---\n_Auto-generated by the docs-sync workflow. '
    printf 'Triggered by [bolt-react-native-sdk PR #%s](%s)._\n' "$PR_NUMBER" "$SDK_PR_URL"
  } > /tmp/docs_pr_body.txt

  DOCS_PR_URL=$(gh pr create \
    --repo "$BOLT_DOCS_REPO" \
    --head "$BRANCH" \
    --base master \
    --title "$PR_TITLE_TEXT" \
    --body-file /tmp/docs_pr_body.txt)
  echo "Created docs PR: $DOCS_PR_URL"
else
  DOCS_PR_URL="https://github.com/${BOLT_DOCS_REPO}/pull/${EXISTING}"
  echo "Updated existing docs PR: $DOCS_PR_URL"
fi

echo "docs_pr_url=${DOCS_PR_URL}" >> "$GITHUB_OUTPUT"
