---
version: 1

# The title of the Pull Request
title: "chore(deps): snyk dependency upgrade"

# The commit message used when Snyk merges or commits
commit_message: "chore: upgrade {{package_name}} from {{package_from}} to {{package_to}}"

# The main body/description of the Pull Request
description: |
  ## 🛡️ Snyk Security Upgrade

  This automated PR fixes security vulnerabilities found in **{{package_name}}**.

  ### 📋 Changes
  * **Package:** {{package_name}}
  * **Upgrade:** {{package_from}} → {{package_to}}
  * **Issues fixed:** {{issue_count}}

  ### Security Review
  - [x] I have considered and reviewed security implications of this PR and included the summary below.

  #### Security Impact Summary
  The purpose of this PR is to update a dependency which meets the criteria set in snyk.

  ### ⚙️ [Settings](https://app.snyk.io/org/bolt-2.0-production/manage/integrations/github-cloud-app#tests-on-prs)
