// Type declaration for the gitignored boltConfig.ts.
// The real file is generated by `yarn gen-bolt-config` and never committed.
export declare const boltConfig: {
  readonly publishableKey: string;
  readonly environment: 'production' | 'sandbox' | 'staging';
};
