// Type declaration for the gitignored devTelemetryConfig.ts.
// The real file is generated by `yarn gen-dev-telemetry-config` and never committed.
export declare const devTelemetryConfig: {
  readonly enabled: boolean;
  readonly endpoint: string;
  readonly username: string;
  readonly authToken: string;
};
