name: Release & Publish

on:
  push:
    branches: [main]

jobs:
  ci:
    # Skip if the push is a release commit (to avoid infinite loop)
    if: "!startsWith(github.event.head_commit.message, 'chore: release')"
    uses: ./.github/workflows/ci.yml

  release-and-publish:
    name: Release & Publish
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLIC_FINEGRAINED_BOLT_CI_GHA_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "bolt-ci"
          git config user.email "bolt-ci@bolt.com"

      - uses: ./.github/actions/setup

      - name: Release version
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_FINEGRAINED_BOLT_CI_GHA_TOKEN }}

      - name: Setup npm registry
        uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: yarn prepare

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
