name: PR description check
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  check:
    # Temporarily disabled due to issues with the reusable workflow
    # uses: BoltApp/actions-reusable-workflows/.github/workflows/pr-description-check.yaml@v1
    runs-on: ubuntu-latest
    steps:
      - name: Always pass
        run: echo "PR description check is temporarily disabled"
